import 'word.dart';

Map text = russian;

const Map english = {
  // Languages
  Language.english : '🇬🇧 English',
  Language.russian : '🇷🇺 Russian',
  Language.french : '🇫🇷 French',
  Language.german : '🇩🇪 German',

  // UI
  'Confirm' : 'Confirm',
  'New meaning' : 'Add new meaning',
  'Enter description' : 'Enter description',
  'Enter image URL (optional)' : 'Enter image URL (optional)',
  'New word' : 'New word',
  'Enter spelling' : 'Provide spelling',
  'Select a language' : 'Select a language',
  'Add new word' : 'Add new word',
  'Dictionary' : 'Dictionary',
  'Delete meaning from word' : 'Delete meaning from word',
  'Deletion' : 'Deletion',
  'Are you sure you want to remove this meaning from this word?' : 'Are you sure you want to remove this meaning from this word?',
  'Cancel' : 'Cancel',
  'Delete' : 'Delete',
  'Edit meaning' : 'Edit meaning',
  'Cancel changes' : 'Cancel changes',
  'Save changes' : 'Save changes',
  'Details' : 'Details',
  'Linking' : 'Linking',
  'Add new meaning' : 'Add new meaning',
  'Select one of the meanings below or add a new one' : 'Select one of the meanings below or add a new one',
  'These words do not have any meaning. Add it yourself.' : 'These words do not have any meaning. Add it yourself.',
  'Link with another word' : 'Link with another word',
  'Delete word from the dictionary' : 'Delete word from the dictionary',
  'Are you sure you want to delete this word from the dictionary?' : 'Are you sure you want to delete this word from the dictionary?',
  'Edit word' : 'Edit word',
  'Search for a word' : 'Search for a word',
  'There is no such word in the dictionary' : 'There is no such word in the dictionary',
  'The dictionary is empty' : 'The dictionary is empty',
  'Added:' : 'Added:',
  'Language:' : 'Language:',
  'Spelling:' : 'Spelling:',
  'Meanings:' : 'Meanings:',
};

const Map russian = {
  // Languages
  Language.english : '🇬🇧 Английский',
  Language.russian : '🇷🇺 Русский',
  Language.french : '🇫🇷 Французский',
  Language.german : '🇩🇪 Немецкий',

  // UI
  'Confirm' : 'Подтвердить',
  'New meaning' : 'Новое значение',
  'Enter description' : 'Введите описание',
  'Enter image URL (optional)' : 'Введите ссылку на изображение (необязательно)',
  'New word' : 'Новое слово',
  'Enter spelling' : 'Введите написание',
  'Select a language' : 'Выберите язык',
  'Add new word' : 'Добавить новое слово',
  'Dictionary' : 'Словарь',
  'Delete meaning from word' : 'Удалить значение из слова',
  'Deletion' : 'Удаление',
  'Are you sure you want to remove this meaning from this word?' : 'Вы уверены, что хотите удалить это значение для данного слова?',
  'Cancel' : 'Отмена',
  'Delete' : 'Удалить',
  'Edit meaning' : 'Редактировать значение',
  'Cancel changes' : 'Отменить изменения',
  'Save changes' : 'Сохранить изменения',
  'Details' : 'Подробно',
  'Linking' : 'Связывание',
  'Add new meaning' : 'Добавить новое значение',
  'Select one of the meanings below or add a new one' : 'Выберите одно из значений ниже или добавьте новое',
  'These words do not have any meaning. Add it yourself.' : 'Эти слова не имеют значений. Добавьте самостоятельно.',
  'Link with another word' : 'Связать с другим словом',
  'Delete word from the dictionary' : 'Удалить слово из словаря',
  'Are you sure you want to delete this word from the dictionary?' : 'Вы уверены, что хотите удалить это слово из словаря?',
  'Edit word' : 'Редактировать слово',
  'Search for a word' : 'Поиск по слову',
  'There is no such word in the dictionary' : 'Этого слова нет в словаре',
  'The dictionary is empty' : 'Словарь пуст',
  'Added:' : 'Добавлено:',
  'Language:' : 'Язык:',
  'Spelling:' : 'Написание:',
  'Meanings:' : 'Значения:',
};